editado_back/cotebiz_virtual/core/urls.py
from django.urls import path
from core import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('login_user/submit', views.login_submit, name='login_submit'),
    path('logout/', views.logout_user, name='logout_user'),
    path('', views.index, name='index'),
    path('enviar_email_fornecedor/', views.enviar_email_fornecedor, name='enviar_email_fornecedor'),   
    path('send_email/', views.SendFormEmail.as_view(), name='send_email'),
    path('cadastrar_fornecedor/', views.cadastrar_fornecedor, name='cadastrar_fornecedor'),
    path('criar_pedido/', views.criar_pedido, name='criar_pedido'),
    path('criar_pedido/submit', views.criar_pedido_submit, name='criar_pedido_submit'),
    path('listar_fornecedores/', views.listar_fornecedores, name='listar_fornecedores'),
    path('listar_produtos_cotados/', views.listar_produtos_cotados, name='listar_produtos_cotados'),
    path('listar_pedidos/', views.listar_pedidos, name='listar_pedidos'),
    path('listar_salas_de_leilao/', views.listar_salas_de_leilao, name='listar_salas_de_leilao'),
    path('detalhar_fornecedor/<int:id>/', views.detalhar_fornecedor, name='detalhar_fornecedor'),
    path('detalhar_pedido/<int:id>/', views.detalhar_pedido, name='detalhar_pedido'),
    path('detalhar_produtos_cotados/<int:id>/', views.detalhar_produtos_cotados, name='detalhar_produtos_cotados'),
    path('detalhar_pedido_da_sala_de_leilao/<int:id>/', views.detalhar_pedido_da_sala_de_leilao, name='detalhar_pedido_da_sala_de_leilao'),
    path('detalhar_pedido_da_sala_de_leilao/<int:id>/submit', views.detalhar_pedido_da_sala_de_leilao_submit, name='detalhar_pedido_da_sala_de_leilao_submit'),
    path('atualizar_fornecedor/<int:id>/', views.atualizar_fornecedor, name='atualizar_fornecedor'),
    path('deletar_fornecedor/<int:id>/', views.deletar_fornecedor, name='deletar_fornecedor'),
    path('resetar_senha/', auth_views.PasswordResetView.as_view(template_name="resetar_senha.html"), name="resetar_senha" ),
    path('enviar_email_para_resetar_senha/', auth_views.PasswordResetDoneView.as_view(template_name="enviar_email_para_resetar_senha.html"), name="enviar_email_para_resetar"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="alterar_senha.html"), name="alterar_senha"),
    path('senha_alterada/', auth_views.PasswordResetCompleteView.as_view(template_name="senha_alterada.html"), name="senha_alterada"),
]

editado_back/cotebiz_virtual/cotebiz_virtual/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views

from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404=views.error404

editado_back/cotebiz_virtual/core/models.py
from django.db import models
from django.contrib.auth.models import User

class Fornecedor(models.Model):
    fornecedor = models.CharField('Nome Fantasia', max_length=40, unique=True)
    razao_social = models.CharField('Razão Social.', max_length=80)
    cnpj = models.CharField('CNPJ',max_length=18)
    inscricao_estadual = models.CharField('I.Estadual:',max_length=15)
    categoria_choices = (
                ('Material de Limpeza e Higiene','Material de Limpeza e Higiene'),
                ('Material de Copa','Material de Copa'),
                ('Alimentos em Geral', 'Alimentos em Geral'),
                ('Frutas e Verduras', 'Frutas e Verduras'),
                ('Material de Escritório', 'Material de Escritório'),
                ('Bebidas', 'Bebidas'),
                ('Descartáveis e Embalagens', 'Descartáveis e Embalagens'),
                ('Itens de Manutenção Básica', 'Itens de Manutenção Básica'),
    )
    categoria = models.CharField(max_length=100, choices=categoria_choices)
    cep = models.CharField('CEP', max_length=11)
    rua = models.CharField('Rua', max_length=100)
    bairro = models.CharField('Bairro', max_length=30)
    cidade = models.CharField('Cidade', max_length=30)
    uf = models.CharField('UF', max_length=30)
    numero = models.CharField('Número', max_length=10)
    telefone = models.CharField('Telefone', max_length=16, null=True, blank=True)
    celular = models.CharField('Celular', max_length=17, null=True, blank=True)
    email = models.CharField('Email', max_length=150, null=True, blank=True)
    observacao = models.CharField('Observação', max_length=400, null=True, blank=True)


    class Meta:
        verbose_name ='Fornecedor'
        verbose_name_plural ='Fornecedores'

    def __str__(self):
        return str(self.fornecedor)


class Pedido_de_cotacao(models.Model):
    data_agora = models.DateTimeField()
    n_pedido = models.CharField('Numero do pedido', max_length=10, null=True, blank=True)
    nome = models.CharField('Nome Fantasia', max_length=40)
    razao_social = models.CharField('Razão Social', max_length=80)
    cnpj = models.CharField('CNPJ', max_length=18)
    plano = models.CharField('Tipo do Plano', max_length=1)
    cep = models.CharField('CEP', max_length=11)
    rua = models.CharField('Rua', max_length=100)
    bairro = models.CharField('Bairro', max_length=30)
    cidade = models.CharField('Cidade', max_length=30)
    numero = models.CharField('Número', max_length=10)
    telefone = models.CharField('Telefone', max_length=16)
    celular = models.CharField('Celular', max_length=17)
    email = models.EmailField('Email', max_length=150)
    n_leilao = models.CharField('Numero do leilão', max_length=10, null=True, blank=True)
    produto1 = models.CharField('Produto 1', max_length=25)
    categoria1 = models.CharField('Categoria 1', max_length=100)
    valor_base1 = models.CharField('Valor Base 1', max_length=9)
    unidade_medida1 = models.CharField('Unidade de Medida 1', max_length=9)
    quantidade1 = models.CharField('Quantidade 1', max_length=5)
    marca1 = models.CharField('Marca 1', max_length=9)
    

    produto2 = models.CharField('Produto 2', max_length=25, null=True, blank=True)
    categoria2 = models.CharField('Categoria 2', max_length=100, null=True, blank=True)
    valor_base2 = models.CharField('Valor Base 2', max_length=9, null=True, blank=True)
    unidade_medida2 = models.CharField('Unidade de Medida 2', max_length=9, null=True, blank=True)
    quantidade2 = models.CharField('Quantidade 2', max_length=5, null=True, blank=True)
    marca2 = models.CharField('Marca 2', max_length=9, null=True, blank=True)


    produto3 = models.CharField('Produto 3 ', max_length=25, null=True, blank=True)
    categoria3 = models.CharField('Categoria 3', max_length=100, null=True, blank=True)
    valor_base3 = models.CharField('Valor Base 3', max_length=9, null=True, blank=True)
    unidade_medida3 = models.CharField('Unidade de Medida 3', max_length=9, null=True, blank=True)
    quantidade3 = models.CharField('Quantidade 3', max_length=5, null=True, blank=True)
    marca3 = models.CharField('Marca 3', max_length=9, null=True, blank=True)


    
    produto4 = models.CharField('Produto 4', max_length=25, null=True, blank=True)
    categoria4 = models.CharField('Categoria 4', max_length=100, null=True, blank=True)
    valor_base4 = models.CharField('Valor Base 4', max_length=9, null=True, blank=True)
    unidade_medida4 = models.CharField('Unidade de Medida 4', max_length=9, null=True, blank=True)
    quantidade4 = models.CharField('Quantidade 4', max_length=5, null=True, blank=True)
    marca4 = models.CharField('Marca 4', max_length=9, null=True, blank=True)


    produto5 = models.CharField('Produto 5', max_length=25, null=True, blank=True)
    categoria5 = models.CharField('Categoria 5', max_length=100, null=True, blank=True)
    valor_base5 = models.CharField('Valor Base 5', max_length=9, null=True, blank=True)
    unidade_medida5 = models.CharField('Unidade de Medida 5', max_length=9, null=True, blank=True)
    quantidade5 = models.CharField('Quantidade 5', max_length=5, null=True, blank=True)
    marca5 = models.CharField('Marca 5', max_length=9, null=True, blank=True)


    produto6 = models.CharField('Produto 6', max_length=25, null=True, blank=True)
    categoria6 = models.CharField('Categoria 6', max_length=100, null=True, blank=True)
    valor_base6 = models.CharField('Valor Base 6', max_length=9, null=True, blank=True)
    unidade_medida6 = models.CharField('Unidade de Medida 6', max_length=9, null=True, blank=True)
    quantidade6 = models.CharField('Quantidade 6', max_length=5, null=True, blank=True)
    marca6 = models.CharField('Marca 6', max_length=9, null=True, blank=True)


    produto7 = models.CharField('Produto 7', max_length=25, null=True, blank=True)
    categoria7 = models.CharField('Categoria 7', max_length=100, null=True, blank=True)
    valor_base7 = models.CharField('Valor Base 7', max_length=9, null=True, blank=True)
    unidade_medida7 = models.CharField('Unidade de Medida 7', max_length=9, null=True, blank=True)
    quantidade7 = models.CharField('Quantidade 7', max_length=5, null=True, blank=True)
    marca7 = models.CharField('Marca 7', max_length=9, null=True, blank=True)


    produto8 = models.CharField('Produto 8', max_length=25, null=True, blank=True)
    categoria8 = models.CharField('Categoria 8', max_length=100, null=True, blank=True)
    valor_base8 = models.CharField('Valor Base 8', max_length=9, null=True, blank=True)
    unidade_medida8 = models.CharField('Unidade de Medida 8', max_length=9, null=True, blank=True)
    quantidade8 = models.CharField('Quantidade 8', max_length=5, null=True, blank=True)
    marca8 = models.CharField('Marca 8', max_length=9, null=True, blank=True)


    produto9 = models.CharField('Produto 9', max_length=25, null=True, blank=True)
    categoria9 = models.CharField('Categoria 9', max_length=100, null=True, blank=True)
    valor_base9 = models.CharField('Valor Base 9', max_length=9, null=True, blank=True)
    unidade_medida9 = models.CharField('Unidade de Medida 9', max_length=9, null=True, blank=True)
    quantidade9 = models.CharField('Quantidade 9', max_length=5, null=True, blank=True)
    marca9 = models.CharField('Marca 9', max_length=9, null=True, blank=True)


    produto10 = models.CharField('Produto 10', max_length=25, null=True, blank=True)
    categoria10 = models.CharField('Categoria 10', max_length=100, null=True, blank=True)
    valor_base10 = models.CharField('Valor Base 10', max_length=9, null=True, blank=True)
    unidade_medida10 = models.CharField('Unidade de Medida 10', max_length=9, null=True, blank=True)
    quantidade10 = models.CharField('Quantidade10', max_length=5, null=True, blank=True)
    marca10 = models.CharField('Marca 10', max_length=9, null=True, blank=True)


    produto11 = models.CharField('Produto 11', max_length=25, null=True, blank=True)
    categoria11 = models.CharField('Categoria 11', max_length=100, null=True, blank=True)
    valor_base11 = models.CharField('Valor Base 11', max_length=9, null=True, blank=True)
    unidade_medida11 = models.CharField('Unidade de Medida 11', max_length=9, null=True, blank=True)
    quantidade11 = models.CharField('Quantidade 11', max_length=5, null=True, blank=True)
    marca11 = models.CharField('Marca 11', max_length=9, null=True, blank=True)


    produto12 = models.CharField('Produto 12', max_length=25, null=True, blank=True)
    categoria12 = models.CharField('Categoria 12', max_length=100, null=True, blank=True)
    valor_base12 = models.CharField('Valor Base 12', max_length=9, null=True, blank=True)
    unidade_medida12 = models.CharField('Unidade de Medida 12', max_length=9, null=True, blank=True)
    quantidade12 = models.CharField('Quantidade 12', max_length=5, null=True, blank=True)
    marca12 = models.CharField('Marca 12', max_length=9, null=True, blank=True)


    produto13 = models.CharField('Produto 13', max_length=25, null=True, blank=True)
    categoria13 = models.CharField('Categoria 13', max_length=100, null=True, blank=True)
    valor_base13 = models.CharField('Valor Base 13', max_length=9, null=True, blank=True)
    unidade_medida13 = models.CharField('Unidade de Medida 13', max_length=9, null=True, blank=True)
    quantidade13 = models.CharField('Quantidade 13', max_length=5, null=True, blank=True)
    marca13 = models.CharField('Marca 13', max_length=9, null=True, blank=True)


    produto14 = models.CharField('Produto 14', max_length=25, null=True, blank=True)
    categoria14 = models.CharField('Categoria 14', max_length=100, null=True, blank=True)
    valor_base14 = models.CharField('Valor Base 14', max_length=9, null=True, blank=True)

editado_back/cotebiz_virtual/core/forms.py
from django import forms
from .models import *

class FornecedorForm(forms.ModelForm):
    fornecedor = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', }),required=True, max_length=100)
    razao_social = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', }),required=True, max_length=100)
    cnpj = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', }),required=True, max_length=100)
    inscricao_estadual = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', }),required=False, max_length=100)
    categoria = forms.Select(attrs={'class':'form-control'})
    cep = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),required=True, max_length=100)
    rua = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),required=True, max_length=100)
    bairro = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),required=True, max_length=100)
    cidade = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),required=True, max_length=100)
    uf = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),required=True, max_length=100)
    numero = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),required=True, max_length=100)
    telefone = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}), required=False, max_length=100)
    celular = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}), required=False, max_length=100)
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control', }),required=True, max_length=250)
    observacao = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}), max_length=100, required=False)
    class Meta:
        model = Fornecedor
        fields = ['fornecedor', 'razao_social', 'cnpj', 'inscricao_estadual', 'categoria','cep', 'rua',
                  'bairro', 'cidade', 'uf', 'numero', 'telefone', 'celular', 'email', 'observacao']

editado_back/cotebiz_virtual/core/templates/alterar_senha.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Digite a nova senha</title>
</head>
<body>
    <h1>Digite a nova senha</h1>
    <p>Por favor, informe sua nova senha duas vezes para que possamos verificar se você a digitou corretamente.</p>
    <form method="POST">{% csrf_token %}
       {{ form }}
        <input type="submit" value="Alterar minha senha">
    </form>
</body>
</html>

editado_back/cotebiz_virtual/core/templates/atualizar_fornecedor.html
{% extends "pagina_modelo.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/fornecedor.css' %}">
<form id="myForm" method="POST">{% csrf_token %}
    <div class="container ">
        <h1 class="text-center ">Alteração do fornecedor</h1>
        <div class="botao">
            {% for message in messages %}
                <div class="alert alert-danger">
                    <strong> {{ message }} </strong>
                </div>
            {% endfor %}
        </div>
            <h2>Informações Básicas</h2>
            <hr>
        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="id_fornecedor"><strong>Nome Fantasia:</strong></label>
                {{ form.fornecedor }}
            </div>
        
            <div class="form-group col-md-4">
                <label for="id_razao_social"><strong>Razão Social:</strong></label>
                {{ form.razao_social }}
            </div>
            <div class="form-group col-md-2">
                <label for="id_cnpj"><strong>CNPJ:</strong></label>
                {{ form.cnpj }}
            </div>
            <div class="form-group col-md-2">
                <label for="id_inscricao_estadual"><strong>I.Estadual:</strong></label>
                {{ form.inscricao_estadual }} 
            </div>
            <div class="form-group col-md-12">
                <h2>Tipo de Categoria</h2>
                <hr>
            </div>
            <div class="form-group col-md-12">
                <label for="id_categoria"><strong>Categoria:</strong></label>
                {{ form.categoria }} <a href="/adicionar_categoria/"><img src="/static/imagens/add.png" alt="Adicionar Categoria"></a>
            </div>
            <div class="form-group col-md-12">
                <h2>Localização</h2>
                <hr>
            </div>
            <div class="form-group col-md-2">
                <label for="id_cep"><strong>CEP:</strong></label>
                {{ form.cep }} 
            </div>
            <div class="form-group col-md-4">
                <label for="id_rua"><strong>Rua:</strong></label>
                {{ form.rua }}
            </div>
            <div class="form-group col-md-4">
                <label for="id_bairro"><strong>Bairro:</strong></label>
                {{ form.bairro }}
            </div>
            <div class="form-group col-md-4">
                <label for="id_cidade"><strong>Cidade:</strong></label>
                {{ form.cidade }}
            </div>
            <div class="form-group col-md-1">
                <label for="id_uf"><strong>UF:</strong></label>
                {{ form.uf }}
            </div>
            <div class="form-group col-md-2">
                <label for="id_numero"><strong>Número:</strong></label>
                {{ form.numero }}
            </div>
            <div class="form-group col-md-12">
                <h2>Contato</h2>
                <hr>
            </div>
            <div class="form-group col-md-2">
                <label for="id_telefone"><strong>Telefone:</strong></label>
                {{ form.telefone }}
            </div>
            <div class="form-group col-md-2">
                <label for="id_celular"><strong>Celular:</strong></label>
                {{ form.celular }}
            </div>
            <div class="form-group col-md-6">
                <div>
                    <label for="id_email"><strong>Email:</strong></label>
                </div>
                {{ form.email }} <a href="/adicionar_email_fornecedor/"> <img src="/static/imagens/add.png" alt=""></a>
            </div>
            <div class="form-group col-md-12">
            <h2>Anotação</h2>
            <hr>    
            </div>
            <div class="form-group col-md-12">
                <label for="id_observacao"><strong>Observação:</strong></label>
                {{ form.observacao }}
            </div>
            <div class="form-group col-md-6">
                <button  class="btn btn-primary m-2" type="submit">Salvar</button>
            
                <a href="/listar_fornecedores/">
                    <button type="button" class="btn btn-danger m-2">
                        Cancelar
                    </button>
                </a>
            
            </div>
        </div>

</div>
</form>
{% endblock %}

editado_back/cotebiz_virtual/core/templates/cadastrar_fornecedor.html
{% extends "pagina_modelo.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/fornecedor.css' %}">
<form id="myForm" method="POST">{% csrf_token %}
    <div class="container ">
        <h1 class="text-center ">Cadastro de  Fornecedor</h1>
        <div class="botao">
            {% for message in messages %}
                <div class="alert alert-danger">
                    <strong> {{ message }} </strong>
                </div>
            {% endfor %}
        </div>
            <h2>Informações Básicas</h2>
            <hr>
        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="id_fornecedor"><strong>Nome Fantasia:</strong></label>
                {{ form.fornecedor }}
            </div>
        
            <div class="form-group col-md-4">
                <label for="id_razao_social"><strong>Razão Social:</strong></label>
                {{ form.razao_social }}
            </div>
            <div class="form-group col-md-2">
                <label for="id_cnpj"><strong>CNPJ:</strong></label>
                {{ form.cnpj }}
            </div>
            <div class="form-group col-md-2">
                <label for="id_inscricao_estadual"><strong>I.Estadual:</strong></label>
                {{ form.inscricao_estadual }} 
            </div>
            <div class="form-group col-md-12">
                <h2>Tipo de Categoria</h2>
                <hr>
            </div>
            <div class="form-group col-md-12">
                <label for="id_categoria"><strong>Categoria:</strong></label>
                {{ form.categoria }}
            </div>
            <div class="form-group col-md-12">
                <h2>Localização</h2>
                <hr>
            </div>
            <div class="form-group col-md-2">
                <label for="id_cep"><strong>CEP:</strong></label>
                {{ form.cep }} 
            </div>
            <div class="form-group col-md-4">
                <label for="id_rua"><strong>Rua:</strong></label>
                {{ form.rua }}
            </div>
            <div class="form-group col-md-4">
                <label for="id_bairro"><strong>Bairro:</strong></label>
                {{ form.bairro }}
            </div>
            <div class="form-group col-md-4">
                <label for="id_cidade"><strong>Cidade:</strong></label>
                {{ form.cidade }}
            </div>
            <div class="form-group col-md-1">
                <label for="id_uf"><strong>UF:</strong></label>
                {{ form.uf }}
            </div>
            <div class="form-group col-md-2">
                <label for="id_numero"><strong>Número:</strong></label>
                {{ form.numero }}
            </div>
            <div class="form-group col-md-12">
                <h2>Contato</h2>
                <hr>
            </div>
            <div class="form-group col-md-2">
                <label for="id_telefone"><strong>Telefone:</strong></label>
                {{ form.telefone }}
            </div>
            <div class="form-group col-md-2">
                <label for="id_celular"><strong>Celular:</strong></label>
                {{ form.celular }}
            </div>
            <div class="form-group col-md-6">
                <div>
                    <label for="id_email"><strong>Email:</strong></label>
                </div>
                {{ form.email }} 
            </div>
            <div class="form-group col-md-12">
            <h2>Anotação</h2>
            <hr>    
            </div>
            <div class="form-group col-md-12">
                <label for="id_observacao"><strong>Observação:</strong></label>
                {{ form.observacao }}
            </div>
            <div class="form-group col-md-6">
                <button  class="btn btn-primary m-2" type="submit">Salvar</button>
            
                <a href="/listar_fornecedores/">
                    <button onclick="limpar_campos()" type="button" class="btn btn-danger m-2">
                        Cancelar
                    </button>
                </a>
            </div>
        </div>

</div>
</form>
{% endblock %}

editado_back/cotebiz_virtual/core/templates/detalhar_fornecedor.html
{% extends "pagina_modelo.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/fornecedor.css' %}">
<h1 class="text-center">Detalhes do Fornecedor</h1>
<div class="modal fade" id="modal_confirm">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Deseja realmente Excluir O fornecedor selecionado: {{fornecedor.fornecedor}}?</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body text-right">
                <a href="/delete/{{fornecedor.id}}/">
                    <button type="button" class="btn btn-danger">
                        EXCLUIR
                    </button>
                </a>
                    <button type="button" class="btn btn-default" data-dismiss="modal">
                        CANCELAR
                    </button>
            </div>
        </div>
    </div>
</div>
<div class="container ">
    <h2>Informações Básicas</h2>
    <hr>
    <div class="form-row">
        <div class="form-group col-md-3">
            <label for="id_fornecedor"><strong>Nome Fantasia:</strong></label>
            {{ fornecedor.fornecedor }}
        </div>

        <div class="form-group col-md-3">
            <label for="id_razao_social"><strong>Razão Social:</strong></label>
            {{ fornecedor.razao_social }}
        </div>
        <div class="form-group col-md-3">
            <label for="id_cnpj"><strong>CNPJ:</strong></label>
            {{ fornecedor.cnpj }}
        </div>
        <div class="form-group col-md-3">
            <label for="id_inscricao_estadual"><strong>I.Estadual:</strong></label>
            {{ fornecedor.inscricao_estadual }}
        </div>
        <div class="form-group col-md-12">
            <h2>Tipo de Categoria</h2>
            <hr>
        </div>
        <div class="form-group col-md-12">
            <label for="id_categoria"><strong>Categoria:</strong></label>
            {{ fornecedor.categoria }}
        </div>
        <div class="form-group col-md-12">
            <h2>Localização</h2>
            <hr>
        </div>
        <div class="form-group col-md-3">
            <label for="id_cep"><strong>CEP:</strong></label>
            {{ fornecedor.cep }}
        </div>
        <div class="form-group col-md-3">
            <label for="id_rua"><strong>Rua:</strong></label>
            {{ fornecedor.rua }}
        </div>
        <div class="form-group col-md-3">
            <label for="id_bairro"><strong>Bairro:</strong></label>
            {{ fornecedor.bairro }}
        </div>
        <div class="form-group col-md-3">
            <label for="id_cidade"><strong>Cidade:</strong></label>
            {{ fornecedor.cidade }}
        </div>
        <div class="form-group col-md-3">
            <label for="id_uf"><strong>UF:</strong></label>
            {{ fornecedor.uf }}
        </div>
        <div class="form-group col-md-3">
            <label for="id_numero"><strong>Número:</strong></label>
            {{ fornecedor.numero }}
        </div>
        <div class="form-group col-md-12">
            <h2>Contato</h2>
            <hr>
        </div>
        <div class="form-group col-md-3">
            <label for="id_telefone"><strong>Telefone:</strong></label>
            {{ fornecedor.telefone }}
        </div>
        <div class="form-group col-md-3">
            <label for="id_celular"><strong>Celular:</strong></label>
            {{ fornecedor.celular }}
        </div>
        <div class="form-group col-md-3">
                <label for="id_email"><strong>Email:</strong></label>
            {{ fornecedor.email }}
        </div>
        <div class="form-group col-md-12">
            <h2>Anotação</h2>
            <hr>
        </div>
        <div class="form-group col-md-12">
            <label for="id_observacao"><strong>Observação:</strong></label>
            {{ fornecedor.observacao }}
        </div>
    </div>
    <a href="/atualizar_fornecedor/{{fornecedor.id}}">
        <button type="button" class="btn btn-primary"> Alterar</button>
    </a>
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal_confirm">Excluir</button>
</div>
</div>
</div>
</div>
{% endblock %}

editado_back/cotebiz_virtual/core/templates/resetar_senha.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        {{ form }}
        <input type="submit" name="Enviar email">

    </form>
</body>
</html>